# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Steven M.
tagline:          'Steven MARTINS'
description:      'Quelques articles techniques...'
url:              http://steven-martins.github.io

author:
  name:           'Steven MARTINS'
  url:            https://twitter.com/martins_steven

paginate:         10

# Custom vars
#version:          2.0.0

mygithub:           https://github.com/steven-martins/
linkedin:         https://www.linkedin.com/in/smartins0
